export const CheekChubby = [
  {
    id: "1",
    body: "CURRENTLY WORKING ON THIS PROJECT. IT IS ABOUT 80% COMPLETE AND WILL SOON BE AVAILABLE HERE." 
  }
];
  

export const Kokoveli =[
  {
    id: "1",
    body: "THIS IS THE FOURTH OF MY CURRENT PROJECTS. IT IS ABOUT 10% COMPLETE AND MAY NOT BE AVAILABLE HERE FOR ANOTHER FEW WEEKS."
  }
];
 

export const MurmurAlley = [
  {
    id: "1",
    body:"EXPECT CONTENT HERE SOOOOOOON ..... IN THE MEAN TIME YOU CAN TAKE A LOOK AT MY RESUME FOR MORE DETAILS ABOUT THE PROJECT. THE RESUME HAS A LINK TO THE LIVE PROJECT"  
  }
];



export const TikldMonkey = [
  {
    id: "1",
    body: "THIS IS THE PROJECT YOU ARE CURRENTLY VISITING. I AM WORKING ON ITS DESCRIPTION AND WILL MAKE IT AVAILABLE HERE SOON. IN THE MEAN TIME YOU CAN TAKE A LOOK AT MY RESUME FOR MORE DETAILS ABOUT THIS AND MY OTHER PROJECTS."
  }
];