export const CheekChubby = [
  {
    id: "1",
    body: "Es un text de farciment usat per la indústria de la tipografia i la impremta. Lorem Ipsum ha estat el text estàndard de la indústria des de l'any 1500, quan un impressor desconegut va fer servir una galerada de text i la va mesclar per crear un llibre de mostres tipogràfiques. No només ha sobreviscut cinc segles, sinó que ha fet el salt cap a la creació de tipus de lletra electrònics, romanent essencialment sense canvis. Es va popularitzar l'any 1960 amb el llançament de fulls Letraset que contenien passatges de Lorem Ipsum, i més recentment amb programari d'autoedició com Aldus Pagemaker que inclou versions de Lorem Ipsum. És un fet establert de forma evident que un lector es distraurà amb el contingut llegible d'una pàgina quan miri a la seva composició. El fet de fer servir Lorem Ipsum és perquè conté una distribució més o menys normal de lletres, de forma oposada a quan es fa servir Contingut aquí, contingut aquí, aconseguint així que sembli català llegible. Molts paquets d'autoedició fan servir Lorem Ipsum com el seu model de text, i una cerca per Lorem Ipsum descobrirà molts llocs web encara a les baceroles. Diverses versions han anat evolucionant al llarg dels anys, a vegades per acident, a vegades a propòsit (inserint humor i coses per l'estil). Contràriament a la creença popular, Lorem Ipsum no és només text aleatori. Té les seves arrels en una peça clàssica de la literatura llatina del 45 aC, és a dir, de fa 2000 anys. Richard McClintock, un professor de llatí al Hampden-Sydney College a Virgínia, va buscar una de les paraules més estranyes del llatí, consectetur, procedent d'un dels paràgrafs de Lorem Ipsum, i anant de citació en citació d'aquesta paraula a la literatura clàssica, en va descobrir l'orígen veritable. Lorem ipsum procedeix de les seccions 1.10.32 i 1.10.33 de De Finibus Bonorum et Malorum (Sobre el Bé i el Mal) de Ciceró, escrit l'any 45 aC. Aquest llibre és un tractat sobre la teoria de l'ètica, molt popular durant el Renaixement. La primera línia de Lorem Ipsum, Lorem ipsum dolor sit amet.., prové d'una línia a la secció 1.10.32" 
  },
];
  

export const Kokoveli =[
  {
    id: "1",
    body: "Nunc varius sit amet lacus vel porta. Ut aliquam lectus sed velit maximus vehicula. Suspendisse sed nunc finibus, blandit eros et, porttitor magna. Fusce tincidunt, orci non sagittis mollis, augue est mollis enim, non sodales magna odio eget neque. Phasellus congue, leo sed maximus tristique, justo felis interdum urna, eget sollicitudin arcu velit eu nisi. Nullam rhoncus urna sit amet nisi dignissim ultrices. Ut sit amet nulla ac odio suscipit iaculis sit amet eu nisi. Nulla dui sem, rhoncus eu nisl sed, volutpat dignissim lacus. Pellentesque semper lacinia mi, ut euismod dui facilisis ut. Donec id luctus justo.  Nulla facilisi. Cras in tortor consectetur justo dignissim commodo. Etiam lobortis erat rutrum, eleifend dolor id, cursus dui. Vivamus ullamcorper consequat lobortis. Etiam molestie, arcu ut tristique consectetur, neque dui consequat dolor, vel molestie nisl ligula a quam. Aenean vitae enim nec metus ultrices varius. Fusce non luctus libero, eu tincidunt sapien. Nulla luctus maximus congue.  Maecenas aliquet sit amet nulla et luctus. Duis consequat ipsum risus, ut venenatis purus molestie at. Aenean rutrum ligula quis augue laoreet accumsan. Donec at odio id ligula sagittis tincidunt. Ut ac est lacinia, hendrerit lectus tristique, aliquet magna. Sed nibh felis, blandit eu risus vel, blandit fringilla ipsum. Sed maximus lacus massa, eget commodo purus accumsan sed. Maecenas fringilla leo a aliquet sagittis. Fusce a vestibulum nisi, id ullamcorper nibh. In quis dapibus mi. Proin at diam nibh. Curabitur in tincidunt ipsum. Pellentesque ultrices semper ipsum ut cursus. Pellentesque convallis aliquet ligula, vel sodales libero aliquam finibus. Fusce fermentum magna mi.  Cras aliquet dui vitae velit sagittis, ut placerat quam pharetra. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dignissim, risus in porttitor maximus, velit turpis consectetur quam, vitae sollicitudin ligula orci rutrum felis. Integer eget tincidunt urna. Nunc quis pellentesque dolor. Sed mollis justo nec egestas fringilla. Proin blandit ante augue. Integer vitae mauris vestibulum, facilisis felis non, interdum elit. Pellentesque dictum finibus venenatis. Cras elementum a magna ut dignissim. Mauris eget pellentesque metus. Aenean vestibulum efficitur augue, sed varius lacus sollicitudin et. Quisque mollis elit vitae interdum vehicula", 
  },
];
 

export const MurmurAlley = [
  {
    id: "1",
    body:"Donec ultricies odio vel ipsum facilisis vulputate. Quisque commodo euismod metus nec bibendum. Praesent in eleifend nisl. Nam porta rhoncus felis, sit amet ultricies elit cursus ut. Curabitur non ante commodo, porttitor lorem sed, faucibus odio. Cras eget augue et sapien tempor pellentesque porta eget sapien. Nulla facilisi. Curabitur sit amet placerat urna. Pellentesque accumsan fermentum tortor a vulputate. Nam vel nunc sed metus imperdiet consequat id in eros. Vivamus imperdiet sodales velit, id tristique massa elementum sed. Quisque tempor arcu dolor, sed placerat enim tempus at. Phasellus neque magna, accumsan et libero non, blandit imperdiet nisi. Vestibulum imperdiet interdum tortor, nec pellentesque odio bibendum nec. Mauris nec erat et quam rhoncus maximus a id lorem. Mauris in nunc nibh. Etiam quam nunc, ullamcorper at congue vitae, consectetur dignissim tortor. Nunc sollicitudin dictum dui et iaculis. Fusce eget augue tincidunt, faucibus turpis ac, porttitor ante."  
  },
];



export const TikldMonkey = [
  {
    id: "1",
    body: "Aliquam erat volutpat. Curabitur et volutpat ligula. Pellentesque nulla urna, facilisis quis mauris vitae, tincidunt semper tellus. Sed semper justo sit amet nibh rhoncus, eget commodo libero ultricies. Nunc sed leo feugiat felis ultricies vulputate. Maecenas varius, mi et bibendum maximus, enim nisl viverra diam, a mattis ante augue a nulla. Donec venenatis mollis tincidunt. Suspendisse aliquam egestas tincidunt. Ut ex enim, semper sed scelerisque et, lobortis eu mi. Pellentesque dui elit, interdum eu imperdiet maximus, cursus id nulla. Praesent sodales arcu a mi maximus, a dictum dolor scelerisque. Ut volutpat libero laoreet imperdiet molestie. Vivamus ac imperdiet leo. Curabitur at porta eros, sit amet lacinia est.  Nam interdum tortor eget ultricies molestie. Mauris leo ligula, lacinia vitae dui sagittis, mollis consectetur tellus. Mauris vel dolor scelerisque, ultrices arcu eget, condimentum metus. Curabitur ultrices scelerisque accumsan. Vivamus commodo libero id leo consequat consectetur. Morbi id ligula fermentum lacus bibendum consectetur. Aliquam erat volutpat. Nullam accumsan nisl id justo suscipit placerat. Curabitur in dictum nunc, sed ornare nulla. In sit amet neque tristique lorem tristique egestas in vitae dui. Integer convallis purus est, at molestie odio euismod vel. Nunc finibus blandit est. Nulla varius tincidunt fermentum. Nam maximus ante lorem, in sollicitudin diam semper a."
  },
];